---
- name: Install Docker
  hosts: all
  become: true
  tasks:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

- name: Install Caddy
  hosts: all
  become: true
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
        state: latest
        update_cache: true

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://dl.cloudsmith.io/public/caddy/stable/gpg.key"

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian {{ ansible_distribution_release }} main
        filename: caddy

    - name: Install Caddy
      ansible.builtin.apt:
        name: caddy
        state: latest
        update_cache: true

    - name: Copy custom Caddyfile
      template:
        src: caddy/Caddyfile
        dest: /etc/caddy/

    - name: Restart Caddy
      service:
        name: caddy
        state: restarted

- name: Install Homer
  hosts: all
  become: true
  tasks:
    - name: Create Docker container
      community.docker.docker_container:
        name: homer
        image: b4bz/homer
        ports: 8080:8080
        volumes: homer:/www/assets
        restart_policy: always
